### ISSUE TITLE
[Feature] Skip Desktop Shortcut

### ISSUE THREAD

**Issue by cg-** [kassindornelles/lol-for-linux-installer#20]
I'd recommend adding an option to skip the step that creates a desktop shortcut. Mine crashed out since my home directory isn't at the normal location.

Traceback (most recent call last):
  File "/var/home/cg/Games/league_of_legends/./Install League of Legends (Python).py", line 109, in run
    leagueinstaller.league_install_code(self.game_main_dir, self.game_region_link)
  File "/var/home/cg/Games/league_of_legends/python_src/src/leagueinstaller.py", line 103, in league_install_code
    with open(desktop_file_path, "w") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/home/cg/.local/share/applications/LeagueLauncherPython.desktop'
Aborted (core dumped)

**Comment by kassindornelles** [comment]
do you have XDG_CONFIG_HOME set in your system?

**Comment by kassindornelles** [comment]
i'm interested in what this script will print for you, might be a easy fix if we get the right home folder
[homedir.tar.gz](https://github.com/kassindornelles/lol-for-linux-installer/files/11106217/homedir.tar.gz)

**Comment by cg-** [comment]
it's not set-- but looks like that'll fix it if you add the .config to it.

```
[cg@fedora Downloads]$ toolbox enter league-of-legends 
⬢[cg@toolbox Downloads]$ pwd
/var/home/cg/Downloads
⬢[cg@toolbox Downloads]$ ./homedir.py 
/home/cg/.config
⬢[cg@toolbox Downloads]$ XDG_CONFIG_HOME=/var/home/cg ./homedir.py
/var/home/cg
```

**Comment by kassindornelles** [comment]
that's honestly a unusual place for a home folder, i'm not entirely sure if i want to support such configurations
it would also break the uninstaller script since it can't find the .json we file we (try to) create in .config 

is a lot of work bc the code is not structured to handle that, is targetting standard home folders so hard that adding such option would take a lot of work and kinda doesnt pay off, i can't even test it myself :/

**Comment by cg-** [comment]
no problem! my biggest suggestion would be to add a checkbox/option to create a shortcut on the main gui so it could be bypassed in situations like mine without crashing.

**Comment by cg-** [comment]
ill see if i can send you a PR with it in a bit.

**Comment by cg-** [comment]
see https://github.com/kassindornelles/lol-for-linux-installer/pull/22

**Comment by kassindornelles** [comment]
> see #22

thanks for that, i guess we can close this one now :tada:
