### ISSUE TITLE
Can't launch lol on updated installer

### ISSUE THREAD

**Issue by Gold3nF3nix** [kassindornelles/lol-for-linux-installer#46]
> jonas@localhost ~/G/LOL> /home/jonas/Games/LOL/launch-league-of-legends.py
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
GameMode is not installed or not available.
Traceback (most recent call last):
  File "/home/jonas/Games/LOL/launch-script.py", line 23, in <module>
    subprocess.run(wine_process, env=start_game_vars, check=True)
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
GameMode is not installed or not available.
Traceback (most recent call last):
  File "/home/jonas/Games/LOL/launch-script.py", line 23, in <module>
    subprocess.run(wine_process, env=start_game_vars, check=True)
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
GameMode is not installed or not available.
Traceback (most recent call last):
  File "/home/jonas/Games/LOL/launch-script.py", line 23, in <module>
    subprocess.run(wine_process, env=start_game_vars, check=True)
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
jonas@localhost ~/G/LOL> 

Tested python 3.10 and 3.11 on opensuse TW and Cachyos

**Comment by kassindornelles** [comment]
It is failing to find the wine executable, not much I can do from my end

**Comment by kassindornelles** [comment]
does the "wine" executable exist in "YOURLEAGUEFOLDER/wine/wine-build/bin/"?

**Comment by kassindornelles** [comment]
stale, closing, feel free to return if find out what happened
